### ISSUE TITLE
Doesn't work

### ISSUE THREAD

**Issue by Jeerjmin** [mmarkelov/react-vk#5] opened 2018-09-04 19:15 UTC
Your examples do not work - return a huge bunch of errors.

**Comment by mmarkelov** [comment] 2018-09-05 06:59
@Jeerjmin can you give some more details about problem? Cause I just check them right now - and it is totally fine

**Comment by potatotatoshka** [comment] 2018-09-13 12:47
I think I have the same problem. But only first is a critical. Check out my log
> ReferenceError: regeneratorRuntime is not defined
> (anonymous function)
> node_modules/react-vk/build/API.js:50
>   > 47 | `value: function () {`
>   48 |   `var _init = _asyncToGenerator(`
>   49 |   `/* #__PURE__*/`
>   50 |   `regeneratorRuntime.mark(function _callee() {`
>   51 |     `var apiId, _this$options, version, onlyWidgets;`
>   52 | 
>   53 |    `return regeneratorRuntime.wrap(function _callee$(_context) {`

**Comment by mmarkelov** [comment] 2018-09-14 07:18
@endy-moscow Can you give me details about it? As much as you can, cause I just can't reproduce this problem on my local machine. Thanks!

**Comment by mmarkelov** [comment] 2018-09-14 07:45
@endy-moscow yeah, I got it with codesandbox example - try to figure out and fix it ASAP

**Comment by mmarkelov** [comment] 2018-09-14 08:56
@Jeerjmin @endy-moscow Thank you guys. That is my fault as always. :( 
Now you can try **react-vk@3.0.0** - and I hope it will be ok

**Comment by potatotatoshka** [comment] 2018-09-14 12:35
@mmarkelov Thanks for the quick response. Now I have a another problem. 

My example:
```
import React, { Component } from 'react';
import VK, { Post } from 'react-vk'
class App extends Component {
  render() {
    return (
      <div className="App">
        <Post ownerId={1} postId={45616} hash={'ZMk4b98xpQZMJJRXVsL1ig'} />
      </div>
    );
  }
}

```

Issue:
```
**TypeError: Cannot read property 'Widgets' of undefined**
Post.mount
node_modules/react-vk/lib/Post.js:39
  36 |       postId = _this$props.postId,
  37 |       hash = _this$props.hash,
  38 |       options = _this$props.options;
  **39 |   vk.Widgets.Post(elementId, ownerId, postId, hash, options);**
  40 | };
  41 | 
  42 | _proto.render = function render() {
```

**Comment by mmarkelov** [comment] 2018-09-14 13:03
@endy-moscow You need set **Post** component inside **VK**. Like so:
```javascript
import React, { Component } from 'react';
import VK, { Post } from 'react-vk'
class App extends Component {
  render() {
    return (
      <div className="App">
        <VK apiId={vkApi}>
          <Post ownerId={1} postId={45616} hash="ZMk4b98xpQZMJJRXVsL1ig" />
        </VK>
      </div>
    );
  }
}
```

**Comment by mmarkelov** [comment] 2018-09-14 13:04
@endy-moscow also you can check it [here](https://codesandbox.io/s/yjj0ro9y3v)

**Comment by mmarkelov** [comment] 2019-01-22 11:02
I suppose I can close this issue - it's been a while.

**Closed as completed by mmarkelov** 2019-01-22 11:02 UTC
Labels: bug
